import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import assert from "node:assert/strict";
import {
  detectDialect,
  detectDialectFromInput,
  sqlForDialectDetection,
} from "../src/lib/ddl/detect-dialect.ts";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = join(here, "..", "tests", "fixtures");

const mysqlSql = `CREATE TABLE \`users\` (
  \`id\` INT AUTO_INCREMENT PRIMARY KEY,
  \`email\` VARCHAR(255) NOT NULL
) ENGINE=InnoDB;`;

const pgSql = `CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE
);`;

const sqliteSql = `CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL
) WITHOUT ROWID;`;

const bigquerySql = `CREATE TABLE \`proj.ds.users\` (
  id INT64,
  tags ARRAY<STRING>
);`;

const snowflakeSql = `CREATE TABLE accounts (
  account_id NUMBER AUTOINCREMENT,
  metadata VARIANT
) CLUSTER BY (account_id);`;

const redshiftSql = `CREATE TABLE users (
  user_id BIGINT IDENTITY(1,1),
  email VARCHAR(320) ENCODE ZSTD,
  PRIMARY KEY (user_id)
) DISTSTYLE KEY DISTKEY (user_id);`;

const flinkSql = `CREATE TABLE events (
  event_id BIGINT,
  row_time AS CAST(event_time AS TIMESTAMP(3)),
  WATERMARK FOR row_time AS row_time - INTERVAL '5' SECOND,
  PRIMARY KEY (event_id) NOT ENFORCED
) WITH ('connector' = 'kafka');`;

const hiveSql = `CREATE TABLE events (
  event_id BIGINT,
  payload MAP<STRING, STRING>
)
STORED AS ORC
PARTITIONED BY (dt STRING);`;

const trinoSql = `CREATE SCHEMA hive.analytics WITH (location = 'hdfs://namenode/analytics');
CREATE TABLE hive.analytics.users (
  user_id BIGINT,
  created_at TIMESTAMP(6) WITH TIME ZONE
) WITH (format = 'ORC');`;

const db2Sql = `CREATE TABLE users (
  user_id INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  created_at TIMESTAMP DEFAULT CURRENT TIMESTAMP,
  PRIMARY KEY (user_id)
) IN USERSPACE1 ORGANIZE BY ROW;`;

const files = [{ id: "f1", name: "schema.sql", sql: mysqlSql }];

assert.equal(detectDialect(mysqlSql), "mysql");
assert.equal(detectDialect(pgSql), "postgresql");
assert.equal(detectDialect(sqliteSql), "sqlite");
assert.equal(detectDialect(bigquerySql), "bigquery");
assert.equal(detectDialect(snowflakeSql), "snowflake");
assert.equal(detectDialect(redshiftSql), "redshift");
assert.equal(detectDialect(flinkSql), "flink");
assert.equal(detectDialect(hiveSql), "hive");
assert.equal(detectDialect(trinoSql), "trino");
assert.equal(detectDialect(db2Sql), "db2");

assert.equal(sqlForDialectDetection("", files), mysqlSql.trim());
assert.equal(sqlForDialectDetection(pgSql, files), mysqlSql.trim());

assert.equal(detectDialectFromInput("", files), "mysql");
assert.equal(detectDialectFromInput(pgSql, []), "postgresql");
assert.equal(detectDialectFromInput("", []), "postgresql");

const pgIdentitySql = `CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);`;
assert.equal(detectDialect(pgIdentitySql), "postgresql");

const bigqueryCommentSql = `-- Table partitioned by event_date for cost control
CREATE TABLE customers (
  customer_id INT64 NOT NULL,
  event_date DATE,
  PRIMARY KEY (customer_id) NOT ENFORCED
);`;
assert.equal(detectDialect(bigqueryCommentSql), "bigquery");

const bigqueryMinimalSql = `CREATE TABLE events (
  event_id STRING NOT NULL,
  amount FLOAT64,
  is_active BOOL
);`;
assert.equal(detectDialect(bigqueryMinimalSql), "bigquery");

assert.equal(detectDialect(readFileSync(join(fixtures, "hive/03-complex.sql"), "utf8")), "hive");
assert.equal(detectDialect(readFileSync(join(fixtures, "bigquery/03-complex.sql"), "utf8")), "bigquery");

console.log("Dialect detection smoke test passed.");
